sudo: required
services:
  - docker

before_install:
  - docker build -t rleee/for-running-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rleee/for-running-react-test npm run test

after_success:
  - docker build -t danlee0150/multi-client ./client
  - docker build -t danlee0150/multi-nginx ./nginx
  - docker build -t danlee0150/multi-server ./server
  - docker build -t danlee0150/multi-worker ./worker
  # Login to docker CLI for pushing docker image to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push docker image to docker hub
  - docker push danlee0150/multi-client
  - docker push danlee0150/multi-nginx
  - docker push danlee0150/multi-server
  - docker push danlee0150/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-976188958134
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
