version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=lee
      - POSTGRES_DB=leedb
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80' # 3050 in local, 80 in container
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules # dont do anything with this folder in the container -
      - ./server:/app # but share/sync the server folder to app folder in container
    environment:
      - REDIS_HOST=redis # name of the service we set up above
      - REDIS_PORT=6379 # default port (can check documentation)
      - PGHOST=postgres
      - PGUSER=lee
      - PGDATABASE=leedb
      - PGPASSWORD=postgres_password # default password (can check documentation)
      - PGPORT=5432 # default port (can check documentation)
      - CHOKIDAR_USEPOLLING=true # server restart every time there is changes from outside container
    depends_on:
      - postgres
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
